apiVersion: v1
kind: Service
metadata:
  name: {{ include "trader.fullname" . }}
  labels: {{- include "trader.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
    app.kubernetes.io/name: {{ include "trader.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
YAML
